# Generated by Django 4.0.1 on 2022-03-22 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinMind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stock_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_data', models.DateTimeField()),
                ('method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pre_stock.finmind')),
                ('stock_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pre_stock.stock_id')),
            ],
            options={
                'ordering': ('-stock_id',),
            },
        ),
    ]
