# Generated by Django 4.0.1 on 2022-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.JSONField(default=123),
            preserve_default=False,
        ),
    ]
